### ISSUE TITLE
Can't start docker container

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [tonywagner/EPlusTV#1]
```
(node:18) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/app/config/state.json',
    at Object.openSync (fs.js:497:3),
    at Object.writeFileSync (fs.js:1528:35),
    at initDirectories (/app/services/init-directories.ts:22:8),
    at /app/index.ts:178:18,
    at Generator.next (<anonymous>),
    at /app/index.ts:8:71,
    at new Promise (<anonymous>),
    at __awaiter (/app/index.ts:4:12),
    at /app/index.ts:177:13,
    at Object.<anonymous> (/app/index.ts:184:3),
(Use `node --trace-warnings ...` to show where the warning was created),
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by m0ngr31** [comment]
Just curious, are you passing in volume for `/app/config`?

I just pushed a change that should fix it if you aren't. Should be on the `latest` tag soon.

**Comment by cookie-monster-bit** [comment]
> Just curious, are you passing in volume for `/app/config`?

Yes, I tried it both ways and got the same error. 

Seems to be fixed now.
