### ISSUE TITLE
Not Signing in to providers---Fixed

### ISSUE THREAD

**Issue by gzowner** [tonywagner/EPlusTV#118]
Getting errors,
Not signing  in to providers to get token keys.

DpzZXJ2aWNlOnRva2VuIiwibmJmIjoxNzI5NjM3NDM0LCJpc3MiOiJ1cm46YmFtdGVjaDpzZXJ2aWNlOmRldmljZSIsImV4cCI6MjU5MzYzNzQzNCwiaWF0IjoxNzI5NjM3NDM0LCJqdGkiOiJkODg3ZTNlZS01YWFmLTRkZDItYmFjOC04MTBlZWQxMzE4MWMifQ.D4IMbha60CigoVRlyODbyLLPFbFAUtsFWp7988fHIUl9Lg8xYTcmuT17916iHsPMJgsh6XXK7SNhQtpu34LXhQ&subject_token_type=urn%3Abamtech%3Aparams%3Aoauth%3Atoken-type%3Adevice'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '617',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /token HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Authorization: Bearer ZXNwbiZicm93c2VyJjEuMC4w.ptUt7QxsteaRruuPmGZFaJByOoqKvDP2a5YkInHrc7c\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Content-Length: 617\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +

**Comment by gzowner** [comment]
TypeError: Cannot read properties of undefined (reading 'refresh_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:1169:53)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Could not get device token exchange
Could not get account grant
Could not get BAM access token
TypeError: Cannot read properties of undefined (reading 'id_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:1123:35)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'assertion')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:1192:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by m0ngr31** [comment]
What version are you using? What provider are you trying to sign into?

**Comment by gzowner** [comment]
latest 4.04. and using standard default espn+. 
ubuntu 20
dont get the popup to link the account

**Comment by m0ngr31** [comment]
Are you using a VPN by chance?

**Comment by gzowner** [comment]
nope

**Comment by m0ngr31** [comment]
I wonder if your container has issues connecting to the internet? Usually I only see that error when someone is using a VPN. ESPN will block connections if it detects specific IP address ranges

**Comment by gzowner** [comment]
nope.. on private IP and residental IP.
> eplustv@4.0.4 start
> ts-node -r tsconfig-paths/register index.tsx

=== E+TV v4.0.4 starting ===
Using ESPN variable is no longer needed. Please use the UI going forward
Using ESPN2 variable is no longer needed. Please use the UI going forward
Using ESPN3 variable is no longer needed. Please use the UI going forward
Using ESPNU variable is no longer needed. Please use the UI going forward
Using SEC variable is no longer needed. Please use the UI going forward
Using SECPLUS variable is no longer needed. Please use the UI going forward
Refreshing auth token (ESPN+)
Could not get auth refresh token
TypeError: Cannot read properties of undefined (reading 'refresh_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:816:35)
    at Generator.next (<anonymous>)
    at /app/services/espn-handler.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/services/espn-handler.ts:4:12)
    at EspnHandler.refreshAuth (/app/services/espn-handler.ts:813:50)
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:831:20)
    at Generator.next (<anonymous>)
    at /app/services/espn-handler.ts:8:71
    at new Promise (<anonymous>)
Refreshing device token (ESPN+)
cRefreshing device refresh token (ESPN+)
Refreshing BAM access token (ESPN+)
TypeError: Cannot read properties of undefined (reading 'id_token')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:1123:35)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
Could not get account grant
TypeError: Cannot read properties of undefined (reading 'assertion')
    at EspnHandler.<anonymous> (/app/services/espn-handler.ts:1192:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/espn-handler.ts:5:58)
Could not get BAM access token
Using FOXSPORTS variable is no longer needed. Please use the UI going forward
TypeError: Cannot read properties of undefined (reading 'accessToken')
    at FoxHandler.<anonymous> (/app/services/fox-handler.ts:483:44)
    at Generator.next (<anonymous>)
    at fulfilled (/app/services/fox-handler.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Updating FOX Sports prelim token
