### ISSUE TITLE
Amazon TNF issues

### ISSUE THREAD

**Issue by adamef93** [tonywagner/EPlusTV#131]
Hate to bug you with another issue, but wanted to let you know about a few things. These aren't game breaking problems

* Both the main feed and the prime vision feed are 30fps/720p for some reason
* There was a moment during the game tonight where the main feed froze and wouldn't buffer past a certain point while the prime vision feed was fine. It doesn't appear this was logged. Either that or the litany of Gotham token errors obscured it. The main feed worked again after maybe 10, 15 minutes. I just tried again after not liking the prime vision feed and it worked. Restarting both my Channels and EPlus containers didn't fix it

I was also curious if it was possible to use the feed from Prime's Twitch channel instead of the Amazon one since the games are available for free without a login on the Twitch channel. This has no bearing on the issues above, it'd just be cool to be able to watch without logging into anything

**Comment by m0ngr31** [comment]
I'll investigate the Twitch feed, that's interesting. The way I'm able to get the streams for NFL is that I have to impersonate a phone, so they keep the quality low for that: just 720p30.

Hard to say for the stream freezing, could be a player issue, internet, or E+. If it's not throwing errors, you can hit the reset channels button in the UI and try again

**Comment by m0ngr31** [comment]
Okay, I changed some code for the TNF tokens + added Twitch. Let me know if you see a difference now

**Comment by adamef93** [comment]
Hate to say it, but the Prime feed is still 30/720 and the Twitch feed doesn't work at all. This is with the latest 4.1.3 build. 

Assuming the Twitch feed can work, would it be possible to have it as an option outside of the NFL+ umbrella since it doesn't require a login to watch?

```
Channel #1 has an active event (Las Vegas Raiders at Kansas City Chiefs). Going to start the stream.
AxiosError: Request failed with status code 403
Could not parse M3U8 properly!
    at settle (/app/node_modules/axios/lib/core/settle.js:19:12)
    at Unzip.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:512:11)
    at Unzip.emit (node:events:529:35)
    at Unzip.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://usher.ttvnw.net/api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={"adblock":false,"authorization":{"forbidden":false,"reason":""},"blackout_enabled":false,"channel":"primevideo","channel_id":168843586,"chansub":{"restricted_bitrates":[],"view_until":1924905600},"ci_gb":false,"geoblock_reason":"","device_id":"ef4a1b1f2a9041b2a63c34b3424868ba","expires":1732911770,"extended_history_allowed":false,"game":"","hide_ads":false,"https_required":true,"mature":false,"partner":false,"platform":"web","player_type":"site","private":{"allowed_to_view":true},"privileged":false,"role":"","server_ads":true,"show_ads":true,"subscriber":false,"turbo":false,"user_id":null,"user_ip":"73.197.231.235","version":2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'usher.ttvnw.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'usher.ttvnw.net',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      write: [Function: writeAfterFIN],
Could not get a playlist for channel #1. Please make sure there is an event scheduled and you have access to it.
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 342419,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 1036,
      [Symbol(kBytesWritten)]: 1246,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={%22adblock%22:false,%22authorization%22:{%22forbidden%22:false,%22reason%22:%22%22},%22blackout_enabled%22:false,%22channel%22:%22primevideo%22,%22channel_id%22:168843586,%22chansub%22:{%22restricted_bitrates%22:[],%22view_until%22:1924905600},%22ci_gb%22:false,%22geoblock_reason%22:%22%22,%22device_id%22:%22ef4a1b1f2a9041b2a63c34b3424868ba%22,%22expires%22:1732911770,%22extended_history_allowed%22:false,%22game%22:%22%22,%22hide_ads%22:false,%22https_required%22:true,%22mature%22:false,%22partner%22:false,%22platform%22:%22web%22,%22player_type%22:%22site%22,%22private%22:{%22allowed_to_view%22:true},%22privileged%22:false,%22role%22:%22%22,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:null,%22user_ip%22:%2273.197.231.235%22,%22version%22:2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: usher.ttvnw.net\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={%22adblock%22:false,%22authorization%22:{%22forbidden%22:false,%22reason%22:%22%22},%22blackout_enabled%22:false,%22channel%22:%22primevideo%22,%22channel_id%22:168843586,%22chansub%22:{%22restricted_bitrates%22:[],%22view_until%22:1924905600},%22ci_gb%22:false,%22geoblock_reason%22:%22%22,%22device_id%22:%22ef4a1b1f2a9041b2a63c34b3424868ba%22,%22expires%22:1732911770,%22extended_history_allowed%22:false,%22game%22:%22%22,%22hide_ads%22:false,%22https_required%22:true,%22mature%22:false,%22partner%22:false,%22platform%22:%22web%22,%22player_type%22:%22site%22,%22private%22:{%22allowed_to_view%22:true},%22privileged%22:false,%22role%22:%22%22,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:null,%22user_ip%22:%2273.197.231.235%22,%22version%22:2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://usher.ttvnw.net/api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={%22adblock%22:false,%22authorization%22:{%22forbidden%22:false,%22reason%22:%22%22},%22blackout_enabled%22:false,%22channel%22:%22primevideo%22,%22channel_id%22:168843586,%22chansub%22:{%22restricted_bitrates%22:[],%22view_until%22:1924905600},%22ci_gb%22:false,%22geoblock_reason%22:%22%22,%22device_id%22:%22ef4a1b1f2a9041b2a63c34b3424868ba%22,%22expires%22:1732911770,%22extended_history_allowed%22:false,%22game%22:%22%22,%22hide_ads%22:false,%22https_required%22:true,%22mature%22:false,%22partner%22:false,%22platform%22:%22web%22,%22player_type%22:%22site%22,%22private%22:{%22allowed_to_view%22:true},%22privileged%22:false,%22role%22:%22%22,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:null,%22user_ip%22:%2273.197.231.235%22,%22version%22:2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 24,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'usher.ttvnw.net',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://usher.ttvnw.net/api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={%22adblock%22:false,%22authorization%22:{%22forbidden%22:false,%22reason%22:%22%22},%22blackout_enabled%22:false,%22channel%22:%22primevideo%22,%22channel_id%22:168843586,%22chansub%22:{%22restricted_bitrates%22:[],%22view_until%22:1924905600},%22ci_gb%22:false,%22geoblock_reason%22:%22%22,%22device_id%22:%22ef4a1b1f2a9041b2a63c34b3424868ba%22,%22expires%22:1732911770,%22extended_history_allowed%22:false,%22game%22:%22%22,%22hide_ads%22:false,%22https_required%22:true,%22mature%22:false,%22partner%22:false,%22platform%22:%22web%22,%22player_type%22:%22site%22,%22private%22:{%22allowed_to_view%22:true},%22privileged%22:false,%22role%22:%22%22,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:null,%22user_ip%22:%2273.197.231.235%22,%22version%22:2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: AxiosHeaders {
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      date: 'Fri, 29 Nov 2024 20:02:50 GMT',
      'access-control-allow-origin': '*',
      'x-amzn-trace-id': 'Root=1-674a1dea-2bf960bb28394182675d6f9e',
      vary: 'accept-encoding',
      'x-cache': 'Error from cloudfront',
      via: '1.1 1af9f97779e52f512a1145b7da36be50.cloudfront.net (CloudFront)',
      'x-amz-cf-pop': 'JFK52-P10',
      'x-amz-cf-id': 'mcYEYuTJXOYga6HhuCA8kVWqcuJTYSZLXMKQkS8Gq8lclrb6qevtWA=='
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [AxiosHeaders],
      method: 'get',
      url: 'https://usher.ttvnw.net/api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={"adblock":false,"authorization":{"forbidden":false,"reason":""},"blackout_enabled":false,"channel":"primevideo","channel_id":168843586,"chansub":{"restricted_bitrates":[],"view_until":1924905600},"ci_gb":false,"geoblock_reason":"","device_id":"ef4a1b1f2a9041b2a63c34b3424868ba","expires":1732911770,"extended_history_allowed":false,"game":"","hide_ads":false,"https_required":true,"mature":false,"partner":false,"platform":"web","player_type":"site","private":{"allowed_to_view":true},"privileged":false,"role":"","server_ads":true,"show_ads":true,"subscriber":false,"turbo":false,"user_id":null,"user_ip":"73.197.231.235","version":2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'GET /api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={%22adblock%22:false,%22authorization%22:{%22forbidden%22:false,%22reason%22:%22%22},%22blackout_enabled%22:false,%22channel%22:%22primevideo%22,%22channel_id%22:168843586,%22chansub%22:{%22restricted_bitrates%22:[],%22view_until%22:1924905600},%22ci_gb%22:false,%22geoblock_reason%22:%22%22,%22device_id%22:%22ef4a1b1f2a9041b2a63c34b3424868ba%22,%22expires%22:1732911770,%22extended_history_allowed%22:false,%22game%22:%22%22,%22hide_ads%22:false,%22https_required%22:true,%22mature%22:false,%22partner%22:false,%22platform%22:%22web%22,%22player_type%22:%22site%22,%22private%22:{%22allowed_to_view%22:true},%22privileged%22:false,%22role%22:%22%22,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:null,%22user_ip%22:%2273.197.231.235%22,%22version%22:2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: usher.ttvnw.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/channel/hls/primevideo.m3u8?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&token={%22adblock%22:false,%22authorization%22:{%22forbidden%22:false,%22reason%22:%22%22},%22blackout_enabled%22:false,%22channel%22:%22primevideo%22,%22channel_id%22:168843586,%22chansub%22:{%22restricted_bitrates%22:[],%22view_until%22:1924905600},%22ci_gb%22:false,%22geoblock_reason%22:%22%22,%22device_id%22:%22ef4a1b1f2a9041b2a63c34b3424868ba%22,%22expires%22:1732911770,%22extended_history_allowed%22:false,%22game%22:%22%22,%22hide_ads%22:false,%22https_required%22:true,%22mature%22:false,%22partner%22:false,%22platform%22:%22web%22,%22player_type%22:%22site%22,%22private%22:{%22allowed_to_view%22:true},%22privileged%22:false,%22role%22:%22%22,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:null,%22user_ip%22:%2273.197.231.235%22,%22version%22:2}&sig=f3ce425a695607a199ec30bff68e50ebdf905051&allow_source=true&allow_audio_only=false',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'usher.ttvnw.net',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: [ [Object] ]
  }
}

```

**Comment by m0ngr31** [comment]
There's nothing I can do for NFL to get above 720p30 since that's all they provide.

I'm away so I can't check the Twitch stream. I'm wondering if it's a DRM thing or something else. I had to test with random channels when I built it. 

If I can get it working, moving it out of the NFL integration is a good idea, but I'll have to figure out how to get the schedule working without being authenticated to NFL

**Comment by adamef93** [comment]
Gotcha, I misunderstood. I thought you said you changed something for the TNF token to try getting a higher resolution feed.

No rush for the Twitch feed!

**Comment by m0ngr31** [comment]
Oh no, I was just trying to keep it from breaking playback 😅

**Comment by adamef93** [comment]
I'm no developer, but is there really no way to impersonate a different device to get a better quality feed? The `DEVICE_INFO` variable in the NFL handler defining a Pixel and the `TV_DEVICE_INFO` variable defining an Onn box. Not sure how it's all being put together, but can't Prime be told that it's using the Onn box instead of the phone? I'm also surprised their mobile streams are capped at 30/720, I would've expected it to scale based on network quality.

Also I think the dream of Twitch might be dead. I completely forgot I tried this with Streamlink last year and they said the streams are DRM'd.

https://github.com/streamlink/streamlink/issues/5592

**Comment by m0ngr31** [comment]
They limit it on their side. They only support playback on mobile devices (except for the random games on NFL Network). I impersonate them separately so you can get Network and RedZone in 1080p and then the games in 720. It's kind of a dumb system

**Comment by m0ngr31** [comment]
That's good info about the Twitch stream, and pretty lame of them. I guess I'll rip it out

**Comment by adamef93** [comment]
> They limit it on their side. They only support playback on mobile devices (except for the random games on NFL Network). I impersonate them separately so you can get Network and RedZone in 1080p and then the games in 720. It's kind of a dumb system

Wow, that's just plain stupid. I know all the NFL+ ads are "watch games on your phone" but I didn't realize it meant the service was ONLY for phones and in limited quality. Is there any way to connect to Prime Video directly for full resolution instead of going through NFL+?

**Comment by m0ngr31** [comment]
Prime uses DRM as well 🫠

**Comment by adamef93** [comment]
RIP

Oddly enough, [the NFL FAQ says they support up to 1080/60,](https://support.nfl.com/hc/en-us/articles/5405696538268-What-is-the-highest-quality-stream-available) so I wonder if this is something with the device being impersonated. Pixel 5 is a bit old these days. Also curious if it's an iOS vs Android thing

**Comment by m0ngr31** [comment]
The "up 1080p" is for when they have random games on NFL Network (I think this year they had a few of the international games)

**Comment by m0ngr31** [comment]
Has TNF been working better now?

**Comment by adamef93** [comment]
Yea, whatever caused it to hiccup that time didn't come back. Who knows what it was, but it's been solid. Thanks!
